services:
  mysql:
    image: mysql:8.4
    container_name: erp-spain-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: erp_spain
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - erp_spain_mysql_data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

volumes:
  erp_spain_mysql_data:
